export const NAV_ICONS = {
  DASHBOARD: "/assets/navIcons/dashboard.svg",
  MAP_3D: "/assets/navIcons/3d-map.svg",
  FLOOR_PLAN: "/assets/navIcons/floor-plan.svg",
  REPORTS: "/assets/navIcons/reports.svg",
  HEALTH: "/assets/navIcons/health.svg",
  MONITORING: "/assets/navIcons/monitoring.svg",
  BUS_TRACKING: "/assets/navIcons/bus-tracking.svg",
  CHILD_TRACKING: "/assets/navIcons/child-tracking.svg",
  SCHOOL_MONITORING: "/assets/navIcons/school-monitoring.svg",
  MAP_2D: "/assets/navIcons/2d-map.svg",
  CONFIGURATION: "/assets/navIcons/configuration.svg",
  SUBJECTS: "/assets/navIcons/subjects.svg",
  TEACHER_CLASS: "/assets/navIcons/teacher-class.svg",
  BUS_ROUTE: "/assets/navIcons/bus-route.svg",
  CLASS_SECTION: "/assets/navIcons/class-section.svg",
  HEALTH_OPTIONS: "/assets/navIcons/health-options.svg",
  SCHEDULING: "/assets/navIcons/scheduling.svg",
  IOT: "/assets/navIcons/iot.svg",
  SMART_WATCHES: "/assets/navIcons/smart-watches.svg",
  SETTINGS: "/assets/navIcons/settings.svg",
  LOGOUT: "/assets/navIcons/logout.svg",
};
