export const countryCodes: { [key: string]: string } = {
  "971": "ae",
  "91": "in",
  "1": "us",
  "93": "af",
  "355": "al",
  "213": "dz",
  "1684": "as",
  "376": "ad",
  "244": "ao",
  "1264": "ai",
  "1268": "ag",
  "54": "ar",
  "374": "am",
  "297": "aw",
  "61": "au",
  "43": "at",
  "994": "az",
  "973": "bh",
  "880": "bd",
  "375": "by",
  "32": "be",
  "501": "bz",
  "229": "bj",
  "591": "bo",
  "267": "bw",
  "55": "br",
  "673": "bn",
  "359": "bg",
  "226": "bf",
  "257": "bi",
  "855": "kh",
  "237": "cm",
  // "1": "ca",
  "238": "cv",
  "56": "cl",
  "86": "cn",
  "57": "co",
  "269": "km",
  "506": "cr",
  "385": "hr",
  "53": "cu",
  "357": "cy",
  "420": "cz",
  "45": "dk",
  "253": "dj",
  "593": "ec",
  "20": "eg",
  "503": "sv",
  "251": "et",
  "358": "fi",
  "33": "fr",
  "995": "ge",
  "49": "de",
  "233": "gh",
  "30": "gr",
  "502": "gt",
  "852": "hk",
  "36": "hu",
  "354": "is",
  "62": "id",
  "98": "ir",
  "964": "iq",
  "353": "ie",
  "972": "il",
  "39": "it",
  "81": "jp",
  "962": "jo",
  "7": "kz",
  "254": "ke",
  "965": "kw",
  "996": "kg",
  "856": "la",
  "961": "lb",
  "218": "ly",
  "352": "lu",
  "853": "mo",
  "389": "mk",
  "60": "my",
  "960": "mv",
  "223": "ml",
  "356": "mt",
  "230": "mu",
  "52": "mx",
  "373": "md",
  "212": "ma",
  "95": "mm",
  "264": "na",
  "977": "np",
  "31": "nl",
  "64": "nz",
  "234": "ng",
  "47": "no",
  "968": "om",
  "92": "pk",
  "507": "pa",
  "63": "ph",
  "48": "pl",
  "351": "pt",
  "974": "qa",
  "40": "ro",
  // "7": "ru",
  "966": "sa",
  "221": "sn",
  "381": "rs",
  "65": "sg",
  "421": "sk",
  "386": "si",
  "27": "za",
  "82": "kr",
  "34": "es",
  "94": "lk",
  "249": "sd",
  "46": "se",
  "41": "ch",
  "963": "sy",
  "886": "tw",
  "66": "th",
  "90": "tr",
  "993": "tm",
  "256": "ug",
  "380": "ua",
  // "971": "ae",
  "44": "gb",
  // "1": "us",
  "598": "uy",
  "998": "uz",
  "58": "ve",
  "84": "vn",
  "967": "ye",
  "260": "zm",
  "263": "zw",
  "262": "yt",
  "383": "xk",
  "681": "wf",
  "678": "vu",
  "1340": "vi",
  "1284": "vg",
  "1784": "vc",
  "690": "tk",
  "1649": "tc",
  "1721": "sx",
  "239": "st",
  "290": "sh",
  "677": "sb",
  "250": "rw",
  "870": "pn",
  "508": "pm",
  "689": "pf",
  "683": "nu",
  "674": "nr",
  "672": "nf",
  "1664": "ms",
  "222": "mr",
};

export const countries = [
  { name: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { name: "India", code: "+91", flag: "🇮🇳" },
  { name: "United States", code: "+1", flag: "🇺🇸" },
  { name: "Afghanistan", code: "+93", flag: "🇦🇫" },
  { name: "Albania", code: "+355", flag: "🇦🇱" },
  { name: "Algeria", code: "+213", flag: "🇩🇿" },
  { name: "American Samoa", code: "+1684", flag: "🇦🇸" },
  { name: "Andorra", code: "+376", flag: "🇦🇩" },
  { name: "Angola", code: "+244", flag: "🇦🇴" },
  { name: "Anguilla", code: "+1264", flag: "🇦🇮" },
  { name: "Antigua and Barbuda", code: "+1268", flag: "🇦🇬" },
  { name: "Argentina", code: "+54", flag: "🇦🇷" },
  { name: "Armenia", code: "+374", flag: "🇦🇲" },
  { name: "Aruba", code: "+297", flag: "🇦🇼" },
  { name: "Australia", code: "+61", flag: "🇦🇺" },
  { name: "Austria", code: "+43", flag: "🇦🇹" },
  { name: "Azerbaijan", code: "+994", flag: "🇦🇿" },
  { name: "Bahrain", code: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", code: "+880", flag: "🇧🇩" },
  { name: "Belarus", code: "+375", flag: "🇧🇾" },
  { name: "Belgium", code: "+32", flag: "🇧🇪" },
  { name: "Belize", code: "+501", flag: "🇧🇿" },
  { name: "Benin", code: "+229", flag: "🇧🇯" },
  { name: "Bolivia", code: "+591", flag: "🇧🇴" },
  { name: "Botswana", code: "+267", flag: "🇧🇼" },
  { name: "Brazil", code: "+55", flag: "🇧🇷" },
  { name: "Brunei", code: "+673", flag: "🇧🇳" },
  { name: "Bulgaria", code: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "+226", flag: "🇧🇫" },
  { name: "Burundi", code: "+257", flag: "🇧🇮" },
  { name: "Cambodia", code: "+855", flag: "🇰🇭" },
  { name: "Cameroon", code: "+237", flag: "🇨🇲" },
  { name: "Canada", code: "+1", flag: "🇨🇦" },
  { name: "Cape Verde", code: "+238", flag: "🇨🇻" },
  { name: "Chile", code: "+56", flag: "🇨🇱" },
  { name: "China", code: "+86", flag: "🇨🇳" },
  { name: "Colombia", code: "+57", flag: "🇨🇴" },
  { name: "Comoros", code: "+269", flag: "🇰🇲" },
  { name: "Costa Rica", code: "+506", flag: "🇨🇷" },
  { name: "Croatia", code: "+385", flag: "🇭🇷" },
  { name: "Cuba", code: "+53", flag: "🇨🇺" },
  { name: "Cyprus", code: "+357", flag: "🇨🇾" },
  { name: "Czech Republic", code: "+420", flag: "🇨🇿" },
  { name: "Denmark", code: "+45", flag: "🇩🇰" },
  { name: "Djibouti", code: "+253", flag: "🇩🇯" },
  { name: "Ecuador", code: "+593", flag: "🇪🇨" },
  { name: "Egypt", code: "+20", flag: "🇪🇬" },
  { name: "El Salvador", code: "+503", flag: "🇸🇻" },
  { name: "Ethiopia", code: "+251", flag: "🇪🇹" },
  { name: "Finland", code: "+358", flag: "🇫🇮" },
  { name: "France", code: "+33", flag: "🇫🇷" },
  { name: "Georgia", code: "+995", flag: "🇬🇪" },
  { name: "Germany", code: "+49", flag: "🇩🇪" },
  { name: "Ghana", code: "+233", flag: "🇬🇭" },
  { name: "Greece", code: "+30", flag: "🇬🇷" },
  { name: "Guatemala", code: "+502", flag: "🇬🇹" },
  { name: "Hong Kong", code: "+852", flag: "🇭🇰" },
  { name: "Hungary", code: "+36", flag: "🇭🇺" },
  { name: "Iceland", code: "+354", flag: "🇮🇸" },
  { name: "Indonesia", code: "+62", flag: "🇮🇩" },
  { name: "Iran", code: "+98", flag: "🇮🇷" },
  { name: "Iraq", code: "+964", flag: "🇮🇶" },
  { name: "Ireland", code: "+353", flag: "🇮🇪" },
  { name: "Mayotte", code: "+262", flag: "🇾🇹" },
  { name: "Kosovo", code: "+383", flag: "🇽🇰" },
  { name: "Wallis and Futuna", code: "+681", flag: "🇼🇫" },
  { name: "Vanuatu", code: "+678", flag: "🇻🇺" },
  { name: "U.S. Virgin Islands", code: "+1340", flag: "🇻🇮" },
  { name: "British Virgin Islands", code: "+1284", flag: "🇻🇬" },
  { name: "Saint Vincent and the Grenadines", code: "+1784", flag: "🇻🇨" },
  { name: "Vatican City", code: "+39", flag: "🇻🇦" },
  { name: "U.S. Minor Outlying Islands", code: "+1", flag: "🇺🇲" },
  { name: "Tokelau", code: "+690", flag: "🇹🇰" },
  { name: "Turks and Caicos Islands", code: "+1649", flag: "🇹🇨" },
  { name: "Sint Maarten", code: "+1721", flag: "🇸🇽" },
  { name: "São Tomé and Príncipe", code: "+239", flag: "🇸🇹" },
  { name: "Saint Helena, Ascension and Tristan da Cunha", code: "+290", flag: "🇸🇭" },
  { name: "Solomon Islands", code: "+677", flag: "🇸🇧" },
  { name: "Rwanda", code: "+250", flag: "🇷🇼" },
  { name: "Réunion", code: "+262", flag: "🇷🇪" },
  { name: "Pitcairn Islands", code: "+870", flag: "🇵🇳" },
  { name: "Saint Pierre and Miquelon", code: "+508", flag: "🇵🇲" },
  { name: "French Polynesia", code: "+689", flag: "🇵🇫" },
  { name: "Niue", code: "+683", flag: "🇳🇺" },
  { name: "Nauru", code: "+674", flag: "🇳🇷" },
  { name: "Norfolk Island", code: "+672", flag: "🇳🇫" },
  { name: "Montserrat", code: "+1664", flag: "🇲🇸" },
  { name: "Mauritania", code: "+222", flag: "🇲🇷" },
  { name: "Macao", code: "+853", flag: "🇲🇴" },
];
